version: 0.2

phases:
  install:
    runtime-versions:
      java: 21
  build:
    commands:
      - echo "Starting build on `date`"
      - echo "Cleaning and packaging Spring Boot project..."
      - chmod +x mvnw
      - ./mvnw clean package -DskipTests
      - mkdir -p build_output
      - cp target/*.jar build_output/pursuit.jar
artifacts:
  files:
    - pursuit.jar
  base-directory: build_output
